import { SCREENWIDTH } from '../core/renderConstants.js';

/**
 * Fuzz offset table for spectre / shadow rendering (r_draw.c).
 * Each entry offsets into the framebuffer by ±SCREENWIDTH.
 */
export const FUZZTABLE = Object.freeze([
  SCREENWIDTH, -SCREENWIDTH, SCREENWIDTH, -SCREENWIDTH, SCREENWIDTH, SCREENWIDTH, -SCREENWIDTH,
  SCREENWIDTH, SCREENWIDTH, -SCREENWIDTH, SCREENWIDTH, SCREENWIDTH, SCREENWIDTH, -SCREENWIDTH,
  SCREENWIDTH, SCREENWIDTH, SCREENWIDTH, -SCREENWIDTH, -SCREENWIDTH, -SCREENWIDTH, -SCREENWIDTH,
  SCREENWIDTH, -SCREENWIDTH, -SCREENWIDTH, SCREENWIDTH, SCREENWIDTH, SCREENWIDTH, SCREENWIDTH, -SCREENWIDTH,
  SCREENWIDTH, -SCREENWIDTH, SCREENWIDTH, SCREENWIDTH, -SCREENWIDTH, -SCREENWIDTH, SCREENWIDTH,
  SCREENWIDTH, -SCREENWIDTH, -SCREENWIDTH, -SCREENWIDTH, -SCREENWIDTH, SCREENWIDTH, SCREENWIDTH,
  SCREENWIDTH, SCREENWIDTH, -SCREENWIDTH, SCREENWIDTH, SCREENWIDTH, -SCREENWIDTH, SCREENWIDTH,
]);

export const FUZZTABLE_SIZE = FUZZTABLE.length;
