/**
 * Monster state tables (info.c — S_POSS_*, S_TROO_*, S_BAR*, S_BEXP*).
 * @typedef {{ sprite: string, frame: number, tics: number, action: string|null, next: string|null, fullbright?: boolean }} MonsterState
 */

/** @type {Record<string, MonsterState>} */
export const POSS_STATES = {
  STND: { sprite: 'POSS', frame: 0, tics: 10, action: 'A_Look', next: 'STND2' },
  STND2: { sprite: 'POSS', frame: 1, tics: 10, action: 'A_Look', next: 'STND' },
  RUN1: { sprite: 'POSS', frame: 0, tics: 4, action: 'A_Chase', next: 'RUN2' },
  RUN2: { sprite: 'POSS', frame: 0, tics: 4, action: 'A_Chase', next: 'RUN3' },
  RUN3: { sprite: 'POSS', frame: 1, tics: 4, action: 'A_Chase', next: 'RUN4' },
  RUN4: { sprite: 'POSS', frame: 1, tics: 4, action: 'A_Chase', next: 'RUN5' },
  RUN5: { sprite: 'POSS', frame: 2, tics: 4, action: 'A_Chase', next: 'RUN6' },
  RUN6: { sprite: 'POSS', frame: 2, tics: 4, action: 'A_Chase', next: 'RUN7' },
  RUN7: { sprite: 'POSS', frame: 3, tics: 4, action: 'A_Chase', next: 'RUN8' },
  RUN8: { sprite: 'POSS', frame: 3, tics: 4, action: 'A_Chase', next: 'RUN1' },
  ATK1: { sprite: 'POSS', frame: 4, tics: 10, action: 'A_FaceTarget', next: 'ATK2' },
  ATK2: { sprite: 'POSS', frame: 5, tics: 8, action: 'A_PosAttack', next: 'ATK3' },
  ATK3: { sprite: 'POSS', frame: 4, tics: 8, action: null, next: 'RUN1' },
  PAIN: { sprite: 'POSS', frame: 6, tics: 3, action: null, next: 'PAIN2' },
  PAIN2: { sprite: 'POSS', frame: 6, tics: 3, action: 'A_Pain', next: 'RUN1' },
  DIE1: { sprite: 'POSS', frame: 7, tics: 5, action: null, next: 'DIE2' },
  DIE2: { sprite: 'POSS', frame: 8, tics: 5, action: 'A_Scream', next: 'DIE3' },
  DIE3: { sprite: 'POSS', frame: 9, tics: 5, action: 'A_Fall', next: 'DIE4' },
  DIE4: { sprite: 'POSS', frame: 10, tics: 5, action: null, next: 'DIE5' },
  DIE5: { sprite: 'POSS', frame: 11, tics: -1, action: null, next: null },
  XDIE1: { sprite: 'POSS', frame: 12, tics: 5, action: null, next: 'XDIE2' },
  XDIE2: { sprite: 'POSS', frame: 13, tics: 5, action: 'A_XScream', next: 'XDIE3' },
  XDIE3: { sprite: 'POSS', frame: 14, tics: 5, action: 'A_Fall', next: 'XDIE4' },
  XDIE4: { sprite: 'POSS', frame: 15, tics: 5, action: null, next: 'XDIE5' },
  XDIE5: { sprite: 'POSS', frame: 16, tics: 5, action: null, next: 'XDIE6' },
  XDIE6: { sprite: 'POSS', frame: 17, tics: 5, action: null, next: 'XDIE7' },
  XDIE7: { sprite: 'POSS', frame: 18, tics: 5, action: null, next: 'XDIE8' },
  XDIE8: { sprite: 'POSS', frame: 19, tics: 5, action: null, next: 'XDIE9' },
  XDIE9: { sprite: 'POSS', frame: 20, tics: -1, action: null, next: null },
};

/** @type {Record<string, MonsterState>} */
export const TROO_STATES = {
  STND: { sprite: 'TROO', frame: 0, tics: 10, action: 'A_Look', next: 'STND2' },
  STND2: { sprite: 'TROO', frame: 1, tics: 10, action: 'A_Look', next: 'STND' },
  RUN1: { sprite: 'TROO', frame: 0, tics: 3, action: 'A_Chase', next: 'RUN2' },
  RUN2: { sprite: 'TROO', frame: 0, tics: 3, action: 'A_Chase', next: 'RUN3' },
  RUN3: { sprite: 'TROO', frame: 1, tics: 3, action: 'A_Chase', next: 'RUN4' },
  RUN4: { sprite: 'TROO', frame: 1, tics: 3, action: 'A_Chase', next: 'RUN5' },
  RUN5: { sprite: 'TROO', frame: 2, tics: 3, action: 'A_Chase', next: 'RUN6' },
  RUN6: { sprite: 'TROO', frame: 2, tics: 3, action: 'A_Chase', next: 'RUN7' },
  RUN7: { sprite: 'TROO', frame: 3, tics: 3, action: 'A_Chase', next: 'RUN8' },
  RUN8: { sprite: 'TROO', frame: 3, tics: 3, action: 'A_Chase', next: 'RUN1' },
  ATK1: { sprite: 'TROO', frame: 4, tics: 8, action: 'A_FaceTarget', next: 'ATK2' },
  ATK2: { sprite: 'TROO', frame: 5, tics: 8, action: 'A_FaceTarget', next: 'ATK3' },
  ATK3: { sprite: 'TROO', frame: 6, tics: 6, action: 'A_TroopAttack', next: 'RUN1' },
  PAIN: { sprite: 'TROO', frame: 7, tics: 2, action: null, next: 'PAIN2' },
  PAIN2: { sprite: 'TROO', frame: 7, tics: 2, action: 'A_Pain', next: 'RUN1' },
  DIE1: { sprite: 'TROO', frame: 8, tics: 8, action: null, next: 'DIE2' },
  DIE2: { sprite: 'TROO', frame: 9, tics: 8, action: 'A_Scream', next: 'DIE3' },
  DIE3: { sprite: 'TROO', frame: 10, tics: 6, action: null, next: 'DIE4' },
  DIE4: { sprite: 'TROO', frame: 11, tics: 6, action: 'A_Fall', next: 'DIE5' },
  DIE5: { sprite: 'TROO', frame: 12, tics: -1, action: null, next: null },
  XDIE1: { sprite: 'TROO', frame: 13, tics: 5, action: null, next: 'XDIE2' },
  XDIE2: { sprite: 'TROO', frame: 14, tics: 5, action: 'A_XScream', next: 'XDIE3' },
  XDIE3: { sprite: 'TROO', frame: 15, tics: 5, action: null, next: 'XDIE4' },
  XDIE4: { sprite: 'TROO', frame: 16, tics: 5, action: 'A_Fall', next: 'XDIE5' },
  XDIE5: { sprite: 'TROO', frame: 17, tics: 5, action: null, next: 'XDIE6' },
  XDIE6: { sprite: 'TROO', frame: 18, tics: 5, action: null, next: 'XDIE7' },
  XDIE7: { sprite: 'TROO', frame: 19, tics: 5, action: null, next: 'XDIE8' },
  XDIE8: { sprite: 'TROO', frame: 20, tics: -1, action: null, next: null },
};

/** @type {Record<string, MonsterState>} */
export const BARREL_STATES = {
  IDLE1: { sprite: 'BAR1', frame: 0, tics: 6, action: null, next: 'IDLE2' },
  IDLE2: { sprite: 'BAR1', frame: 1, tics: 6, action: null, next: 'IDLE1' },
  BEXP1: { sprite: 'BEXP', frame: 0, tics: 5, action: null, next: 'BEXP2', fullbright: true },
  BEXP2: { sprite: 'BEXP', frame: 1, tics: 5, action: 'A_Scream', next: 'BEXP3', fullbright: true },
  BEXP3: { sprite: 'BEXP', frame: 2, tics: 5, action: null, next: 'BEXP4', fullbright: true },
  BEXP4: { sprite: 'BEXP', frame: 3, tics: 10, action: 'A_Explode', next: 'BEXP5', fullbright: true },
  BEXP5: { sprite: 'BEXP', frame: 4, tics: 10, action: null, next: null, fullbright: true },
};

/** @type {Record<string, MonsterState>} */
export const SPOS_STATES = {
  STND: { sprite: 'SPOS', frame: 0, tics: 10, action: 'A_Look', next: 'STND2' },
  STND2: { sprite: 'SPOS', frame: 1, tics: 10, action: 'A_Look', next: 'STND' },
  RUN1: { sprite: 'SPOS', frame: 0, tics: 3, action: 'A_Chase', next: 'RUN2' },
  RUN2: { sprite: 'SPOS', frame: 0, tics: 3, action: 'A_Chase', next: 'RUN3' },
  RUN3: { sprite: 'SPOS', frame: 1, tics: 3, action: 'A_Chase', next: 'RUN4' },
  RUN4: { sprite: 'SPOS', frame: 1, tics: 3, action: 'A_Chase', next: 'RUN5' },
  RUN5: { sprite: 'SPOS', frame: 2, tics: 3, action: 'A_Chase', next: 'RUN6' },
  RUN6: { sprite: 'SPOS', frame: 2, tics: 3, action: 'A_Chase', next: 'RUN7' },
  RUN7: { sprite: 'SPOS', frame: 3, tics: 3, action: 'A_Chase', next: 'RUN8' },
  RUN8: { sprite: 'SPOS', frame: 3, tics: 3, action: 'A_Chase', next: 'RUN1' },
  ATK1: { sprite: 'SPOS', frame: 4, tics: 10, action: 'A_FaceTarget', next: 'ATK2' },
  ATK2: { sprite: 'SPOS', frame: 5, tics: 10, action: 'A_SPosAttack', next: 'ATK3', fullbright: true },
  ATK3: { sprite: 'SPOS', frame: 4, tics: 10, action: null, next: 'RUN1' },
  PAIN: { sprite: 'SPOS', frame: 6, tics: 3, action: null, next: 'PAIN2' },
  PAIN2: { sprite: 'SPOS', frame: 6, tics: 3, action: 'A_Pain', next: 'RUN1' },
  DIE1: { sprite: 'SPOS', frame: 7, tics: 5, action: null, next: 'DIE2' },
  DIE2: { sprite: 'SPOS', frame: 8, tics: 5, action: 'A_Scream', next: 'DIE3' },
  DIE3: { sprite: 'SPOS', frame: 9, tics: 5, action: 'A_Fall', next: 'DIE4' },
  DIE4: { sprite: 'SPOS', frame: 10, tics: 5, action: null, next: 'DIE5' },
  DIE5: { sprite: 'SPOS', frame: 11, tics: -1, action: null, next: null },
  XDIE1: { sprite: 'SPOS', frame: 12, tics: 5, action: null, next: 'XDIE2' },
  XDIE2: { sprite: 'SPOS', frame: 13, tics: 5, action: 'A_XScream', next: 'XDIE3' },
  XDIE3: { sprite: 'SPOS', frame: 14, tics: 5, action: 'A_Fall', next: 'XDIE4' },
  XDIE4: { sprite: 'SPOS', frame: 15, tics: 5, action: null, next: 'XDIE5' },
  XDIE5: { sprite: 'SPOS', frame: 16, tics: 5, action: null, next: 'XDIE6' },
  XDIE6: { sprite: 'SPOS', frame: 17, tics: 5, action: null, next: 'XDIE7' },
  XDIE7: { sprite: 'SPOS', frame: 18, tics: 5, action: null, next: 'XDIE8' },
  XDIE8: { sprite: 'SPOS', frame: 19, tics: 5, action: null, next: 'XDIE9' },
  XDIE9: { sprite: 'SPOS', frame: 20, tics: -1, action: null, next: null },
};

/** @type {Record<string, MonsterState>} */
export const SARG_STATES = {
  STND: { sprite: 'SARG', frame: 0, tics: 10, action: 'A_Look', next: 'STND2' },
  STND2: { sprite: 'SARG', frame: 1, tics: 10, action: 'A_Look', next: 'STND' },
  RUN1: { sprite: 'SARG', frame: 0, tics: 2, action: 'A_Chase', next: 'RUN2' },
  RUN2: { sprite: 'SARG', frame: 0, tics: 2, action: 'A_Chase', next: 'RUN3' },
  RUN3: { sprite: 'SARG', frame: 1, tics: 2, action: 'A_Chase', next: 'RUN4' },
  RUN4: { sprite: 'SARG', frame: 1, tics: 2, action: 'A_Chase', next: 'RUN5' },
  RUN5: { sprite: 'SARG', frame: 2, tics: 2, action: 'A_Chase', next: 'RUN6' },
  RUN6: { sprite: 'SARG', frame: 2, tics: 2, action: 'A_Chase', next: 'RUN7' },
  RUN7: { sprite: 'SARG', frame: 3, tics: 2, action: 'A_Chase', next: 'RUN8' },
  RUN8: { sprite: 'SARG', frame: 3, tics: 2, action: 'A_Chase', next: 'RUN1' },
  ATK1: { sprite: 'SARG', frame: 4, tics: 8, action: 'A_FaceTarget', next: 'ATK2' },
  ATK2: { sprite: 'SARG', frame: 5, tics: 8, action: 'A_FaceTarget', next: 'ATK3' },
  ATK3: { sprite: 'SARG', frame: 6, tics: 8, action: 'A_SargAttack', next: 'RUN1' },
  PAIN: { sprite: 'SARG', frame: 7, tics: 2, action: null, next: 'PAIN2' },
  PAIN2: { sprite: 'SARG', frame: 7, tics: 2, action: 'A_Pain', next: 'RUN1' },
  DIE1: { sprite: 'SARG', frame: 8, tics: 8, action: null, next: 'DIE2' },
  DIE2: { sprite: 'SARG', frame: 9, tics: 8, action: 'A_Scream', next: 'DIE3' },
  DIE3: { sprite: 'SARG', frame: 10, tics: 4, action: null, next: 'DIE4' },
  DIE4: { sprite: 'SARG', frame: 11, tics: 4, action: 'A_Fall', next: 'DIE5' },
  DIE5: { sprite: 'SARG', frame: 12, tics: 4, action: null, next: 'DIE6' },
  DIE6: { sprite: 'SARG', frame: 13, tics: -1, action: null, next: null },
};

/** @type {Record<string, MonsterState>} */
export const HEAD_STATES = {
  STND: { sprite: 'HEAD', frame: 0, tics: 10, action: 'A_Look', next: 'STND' },
  RUN1: { sprite: 'HEAD', frame: 0, tics: 3, action: 'A_Chase', next: 'RUN1' },
  ATK1: { sprite: 'HEAD', frame: 1, tics: 5, action: 'A_FaceTarget', next: 'ATK2' },
  ATK2: { sprite: 'HEAD', frame: 2, tics: 5, action: 'A_FaceTarget', next: 'ATK3' },
  ATK3: { sprite: 'HEAD', frame: 3, tics: 5, action: 'A_HeadAttack', next: 'RUN1', fullbright: true },
  PAIN: { sprite: 'HEAD', frame: 4, tics: 3, action: null, next: 'PAIN2' },
  PAIN2: { sprite: 'HEAD', frame: 4, tics: 3, action: 'A_Pain', next: 'PAIN3' },
  PAIN3: { sprite: 'HEAD', frame: 5, tics: 6, action: null, next: 'RUN1' },
  DIE1: { sprite: 'HEAD', frame: 6, tics: 8, action: null, next: 'DIE2' },
  DIE2: { sprite: 'HEAD', frame: 7, tics: 8, action: 'A_Scream', next: 'DIE3' },
  DIE3: { sprite: 'HEAD', frame: 8, tics: 8, action: null, next: 'DIE4' },
  DIE4: { sprite: 'HEAD', frame: 9, tics: 8, action: null, next: 'DIE5' },
  DIE5: { sprite: 'HEAD', frame: 10, tics: 8, action: 'A_Fall', next: 'DIE6' },
  DIE6: { sprite: 'HEAD', frame: 11, tics: -1, action: null, next: null },
};

/** @type {Record<string, MonsterState>} */
export const BOSS_STATES = {
  STND: { sprite: 'BOSS', frame: 0, tics: 10, action: 'A_Look', next: 'STND2' },
  STND2: { sprite: 'BOSS', frame: 1, tics: 10, action: 'A_Look', next: 'STND' },
  RUN1: { sprite: 'BOSS', frame: 0, tics: 3, action: 'A_Chase', next: 'RUN2' },
  RUN2: { sprite: 'BOSS', frame: 0, tics: 3, action: 'A_Chase', next: 'RUN3' },
  RUN3: { sprite: 'BOSS', frame: 1, tics: 3, action: 'A_Chase', next: 'RUN4' },
  RUN4: { sprite: 'BOSS', frame: 1, tics: 3, action: 'A_Chase', next: 'RUN5' },
  RUN5: { sprite: 'BOSS', frame: 2, tics: 3, action: 'A_Chase', next: 'RUN6' },
  RUN6: { sprite: 'BOSS', frame: 2, tics: 3, action: 'A_Chase', next: 'RUN7' },
  RUN7: { sprite: 'BOSS', frame: 3, tics: 3, action: 'A_Chase', next: 'RUN8' },
  RUN8: { sprite: 'BOSS', frame: 3, tics: 3, action: 'A_Chase', next: 'RUN1' },
  ATK1: { sprite: 'BOSS', frame: 4, tics: 8, action: 'A_FaceTarget', next: 'ATK2' },
  ATK2: { sprite: 'BOSS', frame: 5, tics: 8, action: 'A_FaceTarget', next: 'ATK3' },
  ATK3: { sprite: 'BOSS', frame: 6, tics: 8, action: 'A_BruisAttack', next: 'RUN1' },
  PAIN: { sprite: 'BOSS', frame: 7, tics: 2, action: null, next: 'PAIN2' },
  PAIN2: { sprite: 'BOSS', frame: 7, tics: 2, action: 'A_Pain', next: 'RUN1' },
  DIE1: { sprite: 'BOSS', frame: 8, tics: 8, action: null, next: 'DIE2' },
  DIE2: { sprite: 'BOSS', frame: 9, tics: 8, action: 'A_Scream', next: 'DIE3' },
  DIE3: { sprite: 'BOSS', frame: 10, tics: 8, action: null, next: 'DIE4' },
  DIE4: { sprite: 'BOSS', frame: 11, tics: 8, action: 'A_Fall', next: 'DIE5' },
  DIE5: { sprite: 'BOSS', frame: 12, tics: 8, action: null, next: 'DIE6' },
  DIE6: { sprite: 'BOSS', frame: 13, tics: 8, action: null, next: 'DIE7' },
  DIE7: { sprite: 'BOSS', frame: 14, tics: -1, action: 'A_BossDeath', next: null },
};

/** @type {Record<string, MonsterState>} */
export const SKULL_STATES = {
  STND: { sprite: 'SKUL', frame: 0, tics: 10, action: 'A_Look', next: 'STND2', fullbright: true },
  STND2: { sprite: 'SKUL', frame: 1, tics: 10, action: 'A_Look', next: 'STND', fullbright: true },
  RUN1: { sprite: 'SKUL', frame: 0, tics: 6, action: 'A_Chase', next: 'RUN2', fullbright: true },
  RUN2: { sprite: 'SKUL', frame: 1, tics: 6, action: 'A_Chase', next: 'RUN1', fullbright: true },
  ATK1: { sprite: 'SKUL', frame: 2, tics: 10, action: 'A_FaceTarget', next: 'ATK2', fullbright: true },
  ATK2: { sprite: 'SKUL', frame: 3, tics: 4, action: 'A_SkullAttack', next: 'ATK3', fullbright: true },
  ATK3: { sprite: 'SKUL', frame: 2, tics: 4, action: null, next: 'ATK4', fullbright: true },
  ATK4: { sprite: 'SKUL', frame: 3, tics: 4, action: null, next: 'ATK3', fullbright: true },
  PAIN: { sprite: 'SKUL', frame: 4, tics: 3, action: null, next: 'PAIN2', fullbright: true },
  PAIN2: { sprite: 'SKUL', frame: 4, tics: 3, action: 'A_Pain', next: 'RUN1', fullbright: true },
  DIE1: { sprite: 'SKUL', frame: 5, tics: 6, action: null, next: 'DIE2', fullbright: true },
  DIE2: { sprite: 'SKUL', frame: 6, tics: 6, action: 'A_Scream', next: 'DIE3', fullbright: true },
  DIE3: { sprite: 'SKUL', frame: 7, tics: 6, action: null, next: 'DIE4', fullbright: true },
  DIE4: { sprite: 'SKUL', frame: 8, tics: 6, action: 'A_Fall', next: 'DIE5', fullbright: true },
  DIE5: { sprite: 'SKUL', frame: 9, tics: 6, action: null, next: 'DIE6' },
  DIE6: { sprite: 'SKUL', frame: 10, tics: 6, action: null, next: null },
};

/** @type {Record<string, MonsterState>} */
export const SPID_STATES = {
  STND: { sprite: 'SPID', frame: 0, tics: 10, action: 'A_Look', next: 'STND2' },
  STND2: { sprite: 'SPID', frame: 1, tics: 10, action: 'A_Look', next: 'STND' },
  RUN1: { sprite: 'SPID', frame: 0, tics: 3, action: 'A_Metal', next: 'RUN2' },
  RUN2: { sprite: 'SPID', frame: 0, tics: 3, action: 'A_Chase', next: 'RUN3' },
  RUN3: { sprite: 'SPID', frame: 1, tics: 3, action: 'A_Chase', next: 'RUN4' },
  RUN4: { sprite: 'SPID', frame: 1, tics: 3, action: 'A_Chase', next: 'RUN5' },
  RUN5: { sprite: 'SPID', frame: 2, tics: 3, action: 'A_Metal', next: 'RUN6' },
  RUN6: { sprite: 'SPID', frame: 2, tics: 3, action: 'A_Chase', next: 'RUN7' },
  RUN7: { sprite: 'SPID', frame: 3, tics: 3, action: 'A_Chase', next: 'RUN8' },
  RUN8: { sprite: 'SPID', frame: 3, tics: 3, action: 'A_Chase', next: 'RUN9' },
  RUN9: { sprite: 'SPID', frame: 4, tics: 3, action: 'A_Metal', next: 'RUN10' },
  RUN10: { sprite: 'SPID', frame: 4, tics: 3, action: 'A_Chase', next: 'RUN11' },
  RUN11: { sprite: 'SPID', frame: 5, tics: 3, action: 'A_Chase', next: 'RUN12' },
  RUN12: { sprite: 'SPID', frame: 5, tics: 3, action: 'A_Chase', next: 'RUN1' },
  ATK1: { sprite: 'SPID', frame: 0, tics: 20, action: 'A_FaceTarget', next: 'ATK2', fullbright: true },
  ATK2: { sprite: 'SPID', frame: 6, tics: 4, action: 'A_SPosAttack', next: 'ATK3', fullbright: true },
  ATK3: { sprite: 'SPID', frame: 7, tics: 4, action: 'A_SPosAttack', next: 'ATK4', fullbright: true },
  ATK4: { sprite: 'SPID', frame: 7, tics: 1, action: 'A_SpidRefire', next: 'ATK2', fullbright: true },
  PAIN: { sprite: 'SPID', frame: 8, tics: 3, action: null, next: 'PAIN2' },
  PAIN2: { sprite: 'SPID', frame: 8, tics: 3, action: 'A_Pain', next: 'RUN1' },
  DIE1: { sprite: 'SPID', frame: 9, tics: 20, action: 'A_Scream', next: 'DIE2' },
  DIE2: { sprite: 'SPID', frame: 10, tics: 10, action: 'A_Fall', next: 'DIE3' },
  DIE3: { sprite: 'SPID', frame: 11, tics: 10, action: null, next: 'DIE4' },
  DIE4: { sprite: 'SPID', frame: 12, tics: 10, action: null, next: 'DIE5' },
  DIE5: { sprite: 'SPID', frame: 13, tics: 10, action: null, next: 'DIE6' },
  DIE6: { sprite: 'SPID', frame: 14, tics: 10, action: null, next: 'DIE7' },
  DIE7: { sprite: 'SPID', frame: 15, tics: 10, action: null, next: 'DIE8' },
  DIE8: { sprite: 'SPID', frame: 16, tics: 10, action: null, next: 'DIE9' },
  DIE9: { sprite: 'SPID', frame: 17, tics: 10, action: null, next: 'DIE10' },
  DIE10: { sprite: 'SPID', frame: 18, tics: 30, action: null, next: 'DIE11' },
  DIE11: { sprite: 'SPID', frame: 18, tics: -1, action: 'A_BossDeath', next: null },
};

/** @type {Record<string, MonsterState>} */
export const CYBER_STATES = {
  STND: { sprite: 'CYBR', frame: 0, tics: 10, action: 'A_Look', next: 'STND2' },
  STND2: { sprite: 'CYBR', frame: 1, tics: 10, action: 'A_Look', next: 'STND' },
  RUN1: { sprite: 'CYBR', frame: 0, tics: 3, action: 'A_Hoof', next: 'RUN2' },
  RUN2: { sprite: 'CYBR', frame: 0, tics: 3, action: 'A_Chase', next: 'RUN3' },
  RUN3: { sprite: 'CYBR', frame: 1, tics: 3, action: 'A_Chase', next: 'RUN4' },
  RUN4: { sprite: 'CYBR', frame: 1, tics: 3, action: 'A_Chase', next: 'RUN5' },
  RUN5: { sprite: 'CYBR', frame: 2, tics: 3, action: 'A_Chase', next: 'RUN6' },
  RUN6: { sprite: 'CYBR', frame: 2, tics: 3, action: 'A_Chase', next: 'RUN7' },
  RUN7: { sprite: 'CYBR', frame: 3, tics: 3, action: 'A_Metal', next: 'RUN8' },
  RUN8: { sprite: 'CYBR', frame: 3, tics: 3, action: 'A_Chase', next: 'RUN1' },
  ATK1: { sprite: 'CYBR', frame: 4, tics: 6, action: 'A_FaceTarget', next: 'ATK2' },
  ATK2: { sprite: 'CYBR', frame: 5, tics: 12, action: 'A_CyberAttack', next: 'ATK3' },
  ATK3: { sprite: 'CYBR', frame: 4, tics: 12, action: 'A_FaceTarget', next: 'ATK4' },
  ATK4: { sprite: 'CYBR', frame: 5, tics: 12, action: 'A_CyberAttack', next: 'ATK5' },
  ATK5: { sprite: 'CYBR', frame: 4, tics: 12, action: 'A_FaceTarget', next: 'ATK6' },
  ATK6: { sprite: 'CYBR', frame: 5, tics: 12, action: 'A_CyberAttack', next: 'RUN1' },
  PAIN: { sprite: 'CYBR', frame: 6, tics: 10, action: 'A_Pain', next: 'RUN1' },
  DIE1: { sprite: 'CYBR', frame: 7, tics: 10, action: null, next: 'DIE2' },
  DIE2: { sprite: 'CYBR', frame: 8, tics: 10, action: 'A_Scream', next: 'DIE3' },
  DIE3: { sprite: 'CYBR', frame: 9, tics: 10, action: null, next: 'DIE4' },
  DIE4: { sprite: 'CYBR', frame: 10, tics: 10, action: null, next: 'DIE5' },
  DIE5: { sprite: 'CYBR', frame: 11, tics: 10, action: null, next: 'DIE6' },
  DIE6: { sprite: 'CYBR', frame: 12, tics: 10, action: 'A_Fall', next: 'DIE7' },
  DIE7: { sprite: 'CYBR', frame: 13, tics: 10, action: null, next: 'DIE8' },
  DIE8: { sprite: 'CYBR', frame: 14, tics: 10, action: null, next: 'DIE9' },
  DIE9: { sprite: 'CYBR', frame: 15, tics: 30, action: null, next: 'DIE10' },
  DIE10: { sprite: 'CYBR', frame: 15, tics: -1, action: 'A_BossDeath', next: null },
};
